# ~/.config/hypr/hyprlock.conf

$font = JetBrainsMono Nerd Font

general {
    hide_cursor = true
    grace = 0
    disable_loading_bar = false
}

background {
    monitor =
    path = /home/declan/Images/wallpapers/champloo1.jpg
    blur_passes = 2
    blur_size = 7
    contrast = 0.9
    brightness = 0.7
}

input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3
    outer_color = rgb(7e9cd8)
    inner_color = rgb(1f1f28)
    font_color = rgb(dcd7ba)
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_size = 90
    font_family = $font
    color = rgb(dcd7ba)
    position = 0, 150
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    font_size = 20
    font_family = $font
    color = rgb(727169)
    position = 0, 60
    halign = center
    valign = center
}
